/* eslint-disable @next/next/no-page-custom-font */
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
        rel="stylesheet"
      />
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      {/* Header/ Navbar */}
      <body className={inter.className}>{children}</body>
      {/* Footer */}
    </html>
  );
}
